name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: 'eu-west-1'
          
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Package artifact
        working-directory: backend
        run: |
          mkdir dist
          zip -r dist/backend.zip *

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          existing_bucket_name: ${{ vars.DEPLOY_BUCKET }}
          application_name: ${{ vars.WEB_APP_NAME }}
          environment_name: ${{ vars.WEB_APP_ENV_NAME }}
          region: ${{ vars.AWS_REGION }}
          version_label: ${{ github.run_id }}
          deployment_package: backend/dist/backend.zip
          wait_for_environment_recovery: 60
